### ISSUE TITLE
Question about line endings and automated testing

### ISSUE THREAD

**Issue by jacobdr** [InsightDataScience/cc-example#7]
Quick question for an admin:

If the automated test process is going to be using some kind of diffing tool, then I am concerned about the role of line endings for the `ft1.txt` and `ft2.txt` outputs. While the spec only mentioned the need to separate word and count using a whitespace for `ft1.txt`, I am wondering if it matters if there is a newline character at the end of this file. The same would apply for `ft2.txt`. 

When I use GNU diff with the `-w` option (`diff -w ft1.txt my_ft1.txt`) on my files I consistently get an expected result, but have had cross-platform issues emerge with newlines and this option not engaged. 

Thanks for the clarification!

**Comment by ddrum001** [comment]
It doesn't matter if you have a newline character at the end of your results, our testing suite will ignore these types of formatting issues, and we would also catch any other formatting issues when we manually review each submission.
