### ISSUE TITLE
Difference in median output format and FAQ 

### ISSUE THREAD

**Issue by pushlog** [InsightDataScience/cc-example#8]
Hi,

The median output format mentioned is 
```sh
11
12.5
14
```

But again, the FAQ says, the ouput should have 2 decimals and gives the example, 
```sh
(i.e. 2.00 instead of 2)
```
which means the output can be
```sh
11.00
12.50
14.00
```

Which one is valid according to test suite?
Thanks.

**Comment by ddrum001** [comment]
Thank you for noticing this, we have corrected the README to reflect the correct precision of two decimal places.

**Comment by pushlog** [comment]
Thank you. 
Corrected my program in the my github repo as well.
